name: Deploy .NET Web API to AWS Elastic Beanstalk

on:
    push:
        branches:
            - "main"
        paths:
            - "Domain/**"
            - "WebAPI/**"

env:
    APPLICATION_NAME: sep4-webapi
    ENVIRONMENT_NAME: Sep4webapi-env
    AWS_REGION: eu-west-1

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup dotnet
              uses: actions/setup-dotnet@v2
              with:
                  dotnet-version: "6.0.x"

            - name: Install dependencies
              working-directory: ./WebAPI
              run: dotnet restore

            - name: Create dotnet deployment folder
              working-directory: ./WebAPI
              run: dotnet publish WebAPI.csproj -c Release -o out

            # - name: Upload deployment folder
            #   uses: actions/upload-artifact@v3
            #   with:
            #       name: sep4-deploy
            #       path: WebAPI/out
            #       retention-days: 1

            - name: Generate deployment folder
              working-directory: WebAPI/out
              run: zip -r ../../deploy.zip ./*

            - name: Deploy to AWS Elastic Beanstalk
              uses: einaregilsson/beanstalk-deploy@v16
              with:
                  aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  application_name: ${{ env.APPLICATION_NAME }}
                  environment_name: ${{ env.ENVIRONMENT_NAME }}
                  version_label: v1-${{ github.sha }}
                  region: ${{ env.AWS_REGION }}
                  deployment_package: deploy.zip

    # deploy:
    #     runs-on: ubuntu-latest
    #     needs: build

    #     steps:
    #         - name: Checkout repo
    #           uses: actions/checkout@v3

    #         - name: Download deployment folder
    #           uses: actions/download-artifact@v2
    #           id: Download
    #           with:
    #               name: sep4-deploy

    #         - name: Generate deployment folder
    #           run: zip -r deploy.zip ./sep4-deploy/*

    #         - name: Deploy to AWS Elastic Beanstalk
    #           uses: einaregilsson/beanstalk-deploy@v16
    #           with:
    #               aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #               aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #               application_name: ${{ env.APPLICATION_NAME }}
    #               environment_name: ${{ env.ENVIRONMENT_NAME }}
    #               version_label: v1-${{ github.sha }}
    #               region: ${{ env.AWS_REGION }}
    #               deployment_package: deploy.zip
