name: Deploy .NET Web API to AWS Elastic Beanstalk

on:
    push:
        branches:
            - "main"
        paths:
            - "Domain/**"
            - "WebAPI/**"

env:
    APPLICATION_NAME: sep4-webapi
    ENVIRONMENT_NAME: Sep4webapi-env
    AWS_REGION: eu-west-1

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup dotnet
              uses: actions/setup-dotnet@v2
              with:
                  dotnet-version: "6.0.x"

            - name: Install Dependencies
              working-directory: ./Test/Sep4Test
              run: dotnet restore

            - name: Build
              working-directory: ./Test/Sep4Test
              run: dotnet build -c Release --no-restore

            - name: Run Tests
              working-directory: ./Test/Sep4Test
              run: dotnet test

    publish:
        needs: test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup dotnet
              uses: actions/setup-dotnet@v2
              with:
                  dotnet-version: "6.0.x"

            - name: Install dependencies
              working-directory: ./WebAPI
              run: dotnet restore ./WebAPI.csproj

            - name: Create dotnet deployment folder
              working-directory: ./WebAPI
              run: dotnet publish WebAPI.csproj -c Release -o out

            - name: Generate deployment folder
              working-directory: WebAPI/out
              run: zip -r ../../deploy.zip ./*

            - name: Deploy to AWS Elastic Beanstalk
              uses: einaregilsson/beanstalk-deploy@v16
              with:
                  aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  application_name: ${{ env.APPLICATION_NAME }}
                  environment_name: ${{ env.ENVIRONMENT_NAME }}
                  version_label: v1-${{ github.sha }}
                  region: ${{ env.AWS_REGION }}
                  deployment_package: deploy.zip
